common: &common_lambda
  create_log_group: false
  log_retention: 7
  runtime: python3.6
  timeout: 30

common_logs: &common_logs
  logs:
    action:
      - logs:PutLogEvents
      - logs:DescribeLogStreams
      - logs:DescribeLogGroups
    resource:
      - '*'

lambdas:
  distribution:
    bucket: ${S3Bucket}
    prefix: ${S3Prefix}

  functions:
    GetAmi:
      handler: get_ami/handler.lambda_handler
      code_uri: ${LambdaFunctionsVersion}/src.zip
      environment:
        TABLE: ${DynamoDbTableName}
        REGION: ${AWS::Region}
      <<: *common_lambda
      policies:
        <<: *common_logs
        dynamo:
          action:
            - dynamodb:Scan
          resource:
            - '*'

    PutAmi:
      handler: put_ami/handler.lambda_handler
      code_uri: ${LambdaFunctionsVersion}/src.zip
      environment:
        TABLE: ${DynamoDbTableName}
        REGION: ${AWS::Region}
      <<: *common_lambda
      policies:
        <<: *common_logs
        dynamo:
          action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          resource:
            - '*'

    HelloWorld:
      handler: hello_world/handler.lambda_handler
      code_uri: ${LambdaFunctionsVersion}/src.zip
      <<: *common_lambda
      policies:
        <<: *common_logs

dynamodb:
  table_name: amis
